# SQLAlchemy conf
SQLALCHEMY_DATABASE_URI = 'mysql://b43258:b43258@localhost/orderme'
SQLALCHEMY_ECHO = True
SQLALCHEMY_RECORD_QUERIES = False
SQLALCHEMY_POOL_SIZE = 5
SQLALCHEMY_POOL_TIMEOUT = 10
SQLALCHEMY_POOL_RECYCLE = 2 * 60 * 60
